travis:
  secure:
    BINSTAR_TOKEN: SdT8VWBbKSRxETdzCErjmenlQ+RZGOY7j2V32XAu39eWUkxpLV8M7a2xrjWFw10dz1Rw3ChddVMq/rzutCbwIunNwNHgCYmsx8XEfueuuI5aqmvgVU2C5YKgFpYBtlNSb9eGsqDnhKSAD1+I44NQmEoLZJXQXy42sCfmRspcs4/0VCpwHiqg+guaYbB9KK2xSx388uVrbHFuj5zcmBaKwOKI8DCW7eXZHITLkhC9ItwitHds7Z2k2+fcc3A6kNriyIXuJ9c68u6J0yy+NYsxgSn51MleZFnFI/hJphPdiPEnR2r1IZZyGFQGs7tWjrgFNo3CK/wffdY1Acct+WDBvuY8zenXdbgYdIehtEeDt2xgnWBqDyjeK1xU+HYeLZELL1KHSAxehYJeQtJf0PJBLxGOz3NmFjDJ76XJYLWekSkv3CdeYk4UiW65p3u6ibfZfgNtm+ROEVJ4kSk+00l+yG7iubz28O5CaihVUxQ/RVvtsqG1LwZntFlqSN49nBvFPn1SOYNjr81NrfIY4BSCPmVz466jSl086sT3bKqcz7EpYZ1x92XUSO2jEuyd9mJkXgkjb9kVCgIeXrgUhDrRtMJvwgn69yEWlyrxph2o01PvsfkqGsGlE/Trg3rmvzAdK6omSDH+1mhuVHccIgvrLppaegmh8OIp9bBoz+Pkk+M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
